### ISSUE TITLE
Coding Competitions Page - Hide the expired contests

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/Algorithmist#10]
Remove the contests from the table which has expired.
 
<img width="1004" alt="Screenshot 2022-11-18 at 3 44 36 PM" src="https://user-images.githubusercontent.com/93304796/202678029-8c256a51-d594-43a3-808d-2eefbb3ef324.png">

**Comment by ThorezNS** [comment]
Hey I would like to work on it

**Comment by Nayaker** [comment]
Ok great, I assign this to you. I have seen your work in the last PR, it would be great if we can arrange a zoom call or google meet. Tell a time in UTC form when you can be available.

**Comment by ThorezNS** [comment]
Thank you, I will be available on zoom tomorrow from 6:00 UTC to 9:00 UTC. I will work on this problem tomorrow or Tuesday

**Comment by Nayaker** [comment]
@ThorezNS there is an update on this one, I want to show the data of the coding competitions whose registration is closed but the completion is yet not completed. And if the completion is currently happening then give it a background color and mark it as competition has started till the time it ends. 

Sheet from where we are pulling the data : https://docs.google.com/spreadsheets/d/1-cTddH1wJRtyKazJuAWHdzK8Wjp1hwf36l3kONy6tE0/edit#gid=0

**Comment by ThorezNS** [comment]
@Nayaker I can work on it tomorrow and Thursday

**Comment by Nayaker** [comment]
Yeah no problem, remember to fork the main branch rather than client

**Comment by ThorezNS** [comment]
Can you specify this task please? Do you want competitions in the list with closed registrations to be displayed, but only those that are not expired? How is this supposed to be done when registration_status is changed with expiration?

**Comment by Nayaker** [comment]
@ThorezNS Check LinkedIn

_<p style="color:blue; text-align:center;">This message will be removed in one hour</p>_

**Comment by Nayaker** [comment]
<img width="1010" alt="Screenshot 2022-11-23 at 9 10 54 PM" src="https://user-images.githubusercontent.com/93304796/203588009-c9e06139-f873-4541-8d1e-b1fbcb00a39a.png">

**Comment by ThorezNS** [comment]
Okay, I'm working on it
