### ISSUE TITLE
Coding Competitions Page - Seconds should be in 10s

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/Algorithmist#11]
I.e., 0 seconds should look like 00 

<img width="1004" alt="Screenshot 2022-11-18 at 8 01 35 PM" src="https://user-images.githubusercontent.com/93304796/202728264-ecf2d0f8-b0c5-4a2f-8af5-31f500c43216.png">

**Comment by Ayushpanditmoto** [comment]
I can do this please assign to me
