### ISSUE TITLE
Update the ReadMe file 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/Algorithmist#12]
Write the readme file for the project by whatever you understand about the project (https://algorithmist-dev.web.app/) in case of anything that you don't understand you can ask it here. Don't worry about the correctness of whatever you write, if will be reviewed and changed. 

I want the structure to be something similar to this : 
<img width="892" alt="Screenshot 2022-11-19 at 11 50 50 AM" src="https://user-images.githubusercontent.com/93304796/202837631-49bf9f02-6e4d-4ff3-a7ce-3367398640bf.png"> <br/>

<img width="907" alt="Screenshot 2022-11-19 at 11 51 11 AM" src="https://user-images.githubusercontent.com/93304796/202837646-75799082-531a-438d-b0e9-e54d1b0fd80d.png">

**Comment by ThePlugJumbo** [comment]
Can I take this one?
