### ISSUE TITLE
Mobile Responsiveness - CSS 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/Algorithmist#17]
The website is primarily currently for the tablet landscape, laptops, and personal computers. We have displayed a dummy text for devices below 1100px. 

- Work on responsiveness 
- Only CSS changes
- 320px to 1100px (same mobile structure)
- You can do one page at a time and generate a PR

**Comment by gogoiakash2311** [comment]
Hey @Nayaker Can you assign this to me

**Comment by Nayaker** [comment]
Hello @gogoiakash2311 great to have you here, I will assign this project to you. 

Please Note : 
    - Do one page at a time, and inform which page you are working on. So that I don't give the same page to anyone else and get a merge conflict. 
    - Write here in comments like **I am working on : landing page and might complete it by 24 Nov**. Something like this, it will be helpful for other people who want to contribute here. 

I have seen your github profile, and loved it. Happy coding.

**Comment by gogoiakash2311** [comment]
Thanks, @Nayaker. Once I look into the project than I'll let you know

**Comment by alisha-takkar** [comment]
Hey @Nayaker please assign me this issue. I'll start with fixing landing page. Thanks!
