### ISSUE TITLE
Coding competitions typos 

### ISSUE THREAD

**Issue by jinitsuga** [Nayaker/Algorithmist#28]
Hey - when I was tackling the filtering issue, I noticed a few typos within the tag filters for the coding competitions. These are the ones I've noticed so far:

- Competiions should be --> Competitions
- Hackethrons should be --> Hackathons
- Competative should be --> Competitive

I would fix these immediately but I'm pretty sure they're coming from the backend? Not entirely sure. Let me know how that's setup and I can take care of it, if you want.

Attaching img for reference.
![algo-typos](https://user-images.githubusercontent.com/73081185/204142750-51ccf9b9-0504-4204-8127-b9909a2982c7.jpg)

**Comment by Nayaker** [comment]
Thanks for noticing, you can change the competitionFilters.js file, and I will take care of the backend. 

@ThorezNS is working on the CodingCompetitions.js file, you can collaborate with him if you wish to work on any other issue on the CodingCompetitions.js file.
