### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by RajMhatre20** [Nayaker/Algorithmist#31]
Can you check the privacy policy that I have generated below so that I can add it to the website?
[PRIVACY POLICY.pdf](https://github.com/Nayaker/Algorithmist/files/10101063/PRIVACY.POLICY.pdf)

**Comment by Nayaker** [comment]
Amazing 🔥, good stuff. Change PrivacyPolicies.js file, the code is in react js but would not be hard for you to understand. And then generate a pull request (PR). In case of any other issues you can ask me here.
