### ISSUE TITLE
Implement redux folder structure on the project

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/Algorithmist#40]
The project is using simple folder structure, but since we are growing it is becoming more and more difficult to maintain without redux. **Implement redux folder structure on the client side of the project.**

![image](https://user-images.githubusercontent.com/93304796/205486769-d2d895ee-e161-4343-8d64-a260aefb7b7e.png)

**Comment by Ravina-Deogadkar** [comment]
Can I work on this issue?

**Comment by Nayaker** [comment]
@Ravina-Deogadkar Sure I am assigning this talk to you, if you face any issues or want to ask something about the project feel free to ask here. Happy Coding 🚀

**Comment by Nayaker** [comment]
Oh ok, no problem, I am sorry I didn't find you in the forks so wrote it. I won't be updating anything till 8 Dec to avoid any merge conflict. Happy coding :)

**Comment by Nayaker** [comment]
Please try to generate a PR in the next 24 hours if possible :)
