### ISSUE TITLE
Responsiveness of landing page

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/Algorithmist#44]
Below 1100 we are not showing any screen on the device. You can check out https://algorithmist-dev.web.app/ by reducing the page size. 

The task is to make the landing page tablet and mobile friendly, the page is already responsive for 1100 and above. 

Happy coding 🚀

**Comment by Lonecloud7** [comment]
can you assign this to me?

**Comment by Nayaker** [comment]
Yeah sure, read the code and change the Landingpage.js file. In case of any doubts, you can ask here :)

**Comment by Lonecloud7** [comment]
@Nayaker thanks might need some help later

**Comment by Nayaker** [comment]
@Lonecloud7 Any update?

**Comment by Lonecloud7** [comment]
Still working on it, it's going well so far
