### ISSUE TITLE
Coding Sheets page more dynamic 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/Algorithmist#47]
### Brief about Coding Sheets page : 
The coding sheets page https://algorithmist-dev.web.app/coding-sheets contains a list of questions that a person will solve and then he can mark when the question is done. 
<br/>

### Task : 
- When a person clicks on the done button, the color of the icon and the background color of the whole row change. A CSS class is already named _done-row_, which can be added with the default _link-row_ class.

    <img width="1021" alt="Screenshot 2022-12-16 at 6 34 17 PM" src="https://user-images.githubusercontent.com/93304796/208104566-2464bea4-d8e9-44e7-97d4-fb7d4d382dee.png">

<img width="1440" alt="Screenshot 2022-12-16 at 6 48 05 PM" src="https://user-images.githubusercontent.com/93304796/208106897-cd288249-69a3-4afe-bbc0-fdeae23d9099.png">

- When done is clicked the top progress would change as well—both the ceil number and the progress bar. The width of the filled progress bar needs to be properly calculated by the total number of questions and the questions completed.

    <img width="534" alt="Screenshot 2022-12-16 at 6 40 29 PM" src="https://user-images.githubusercontent.com/93304796/208105582-afe027e5-ab84-49b3-95f7-6e0dbe122369.png">
<br/>

### Want to contribute : 
- Write in the comment that you want to be assigned this task along with the predicted time required to complete it. 
- Please change only the CodingSheets.js file, or if you would like to change any other page keep me informed. 
- Happy Coding :) 🚀

**Comment by JordanAdair** [comment]
I'd like to be assigned this task, please.

**Comment by Nayaker** [comment]
Sure, @JordanAdair I am assigning this task to you. Do write the estimated time it will require for you to complete the task. 

Happy coding :)

**Comment by JordanAdair** [comment]
As soon as I'm done familiarizing myself with the code-base I expect to be able to complete this within the hour. 
I appreciate the opportunity! :)
