### ISSUE TITLE
Coding Competitions Page - The data should update every minute

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/Algorithmist#9]
Currently, the data being pulled from the API has a date and we are calculating the time left from it only once. The new code should update that time left portion every minute. 

<img width="1004" alt="Screenshot 2022-11-18 at 3 42 46 PM" src="https://user-images.githubusercontent.com/93304796/202677660-9f1fa376-fc89-4b2b-b49a-cdf6e609799a.png">

**Comment by ThorezNS** [comment]
Hey I would like to work on it

**Comment by Nayaker** [comment]
Ok, I am assigning you this then. 

1. Pull the client Branch.
2. Go to src -> Screen -> CodingCompetitions

**Comment by ThorezNS** [comment]
Thank you I'm on it

**Comment by Nayaker** [comment]
It would be great if you can generate the pull request a little sooner

**Comment by ThorezNS** [comment]
Sorry for the delay, I'll send the PR today

**Comment by Nayaker** [comment]
@ThorezNS No problem, do you have a LinkedIn profile?

**Comment by ThorezNS** [comment]
Yes, here is my profile: [https://www.linkedin.com/in/niemiecmaciej/](url)
